### ISSUE TITLE
Notice for not logged in user not showing

### ISSUE THREAD

**Issue by rgott** [rgott/cosc490#19]
login notice `Not Logged In!` is suppose to appear on redirect as specified in in `application_controller.rb` it is not.

**Comment by DonSeannelly** [comment]
Using `alert` instead of `notice` displays the message, like so:
![image](https://cloud.githubusercontent.com/assets/14933100/25951190/f542421e-362a-11e7-82ba-2b42ee997069.png)

Is this the desired functionality? Or are we looking for more of a toast message style?

Also, this configuration will display the alert upon initial navigation to the site, since navigation to root redirects to login. Any ideas on how we might want to solve that?

**Comment by rgott** [comment]
Yes this is desired it was not showing up for me. I will have to re-test

Just change root to login to fix the initial redirect or have the landing page be a page that the user does not have to log in for.
