### ISSUE TITLE
Wrong Requirement Numbers

### ISSUE THREAD

**Issue by DonSeannelly** [rgott/cosc490#7]
The requirement numbers are displaying the wrong requirement number. The section number is correct, but the task number does not reset between sections.
![image](https://cloud.githubusercontent.com/assets/14933100/25364416/58d4177e-2930-11e7-9fd6-3acdc7efd4aa.png)
The above image should read as the following:
4.0
4.1
4.2
4.3
5.0
5.1

**Comment by scott789** [comment]
This is because of this line `<% @requirement.each_with_index do |r, index| %>`. This loop is just iterating over all of the requirements for a category, regardless of their section.

I can identify two solutions:

1. Add a column to each requirement called "requirement_number". This is in the pattern of our current implementation of each requirement storing the section id that it belongs to. This unique requirement id could then be printed by calling `r.requirement_number` in the view.

2. Bump up the Big-O complexity by one power and add a second for loop iteration in the view or controller that iterates through each section. This way the requirements go back to base index 1 after completing a run through a section.

I favor option 1.

**Comment by scott789** [comment]
Commit pending.
