### ISSUE TITLE
Requirement Progress Not Displaying

### ISSUE THREAD

**Issue by DonSeannelly** [rgott/cosc490#8]
The requirement progress is not displaying properly in the deployed version of the application. The database appears to be populated correctly, as the tier calculation is working as expected. The community involvement tab should show 40/100 points, but shows 0/100.

Here is the view on localhost:
![image](https://cloud.githubusercontent.com/assets/14933100/25364536/1e0b24f6-2931-11e7-91ab-14181971b8ac.png)

Here is the view on the Heroku Deployment:
![image](https://cloud.githubusercontent.com/assets/14933100/25364549/32d2c2d6-2931-11e7-8dd3-344503d1a8e9.png)

**Comment by rgott** [comment]
Issue with your event sum method and seed values in the database. Please see the commit for further documentation

**Comment by scott789** [comment]
@rgott I found that the issue was in the ID for seeds data. If you just run `rake db:seed` then it gives the seed data higher and higher IDs. I find that when there are changes to the seed file it is best to run `rake db:reset` which will tear down/up the db structure, rerun migrations, and re-seed the app. This was probably the issue that @DonSeannelly  was encountering.

**Comment by scott789** [comment]
@rgott My table has the `requirement_progress` column. You may need to run the reset command as noted above in order to see it work properly.

![image](https://cloud.githubusercontent.com/assets/18712626/25437694/337af156-2a65-11e7-866f-27bd45b88180.png)

**Comment by scott789** [comment]
Solved this discussion on Slack.
